# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  a_first_test_job:
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      DESIRED_DOCKER_TAG: 5.27.1
      DOCKER_LOGIN_USERNAME: 'ccc'
      DOCKER_LOGIN_SECRET: 'ccc'
    steps:
      - checkout
      - secrethub/install
      - run: |
             echo "A FIRST TEST JOB"
  yet_another_test_job:
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      DESIRED_DOCKER_TAG: 5.27.1
      DOCKER_LOGIN_USERNAME: 'ccc'
      DOCKER_LOGIN_SECRET: 'ccc'
    steps:
      - checkout
      - secrethub/install
      - run: |
             echo "YET ANOTHER TEST WORKFLOW"

workflows:
  version: 2.1
  yet_another_test_workflow:
    jobs:
      - yet_another_test_job:
          context: gravitee-lab
          filters:
            tags:
              # only: /^v.*/
              only: /^*/
  a_first_workflow:
    jobs:
      - yet_another_test_job:
          context: gravitee-lab
          filters:
            tags:
              # only: /^v.*/
              only: /^*/
      - a_first_test_job:
          context: gravitee-lab
          requires:
            yet_another_test_job
          filters:
            tags:
              # only: /^v.*/
              only: /^*/
