# Machine executor, set the machine key to true in .circleci/config.yml:
version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  a_first_test_job:
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      DESIRED_DOCKER_TAG: 5.27.1
      DOCKER_LOGIN_USERNAME: 'ccc'
      DOCKER_LOGIN_SECRET: 'ccc'
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "A FIRST TEST JOB"
          command: |
               echo "A FIRST TEST JOB"
  yet_another_test_job:
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      DESIRED_DOCKER_TAG: 5.27.1
      DOCKER_LOGIN_USERNAME: 'ccc'
      DOCKER_LOGIN_SECRET: 'ccc'
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "YET ANOTHER TEST WORKFLOW"
          command: |
               echo "YET ANOTHER TEST WORKFLOW"

workflows:
  version: 2.1
  product_release:
    jobs:
      - yet_another_test_job:
          context: gravitee-lab
          filters:
            # will run only when on master branch, with a release tag
            tags:
              only:
                - /^rc-*.*.*/
            branches:
              # will not run on pull requests from
              #
              ignore:
                - /^fix*/
                - /^issues*/
                - /^*support/
                - /^*snyk*/
                - /^*dependabot*/
  dev_pr_review:
    jobs:
      - yet_another_test_job:
          context: gravitee-lab
          filters:
            # tags:
              # only:
                # - /^*.*.*/
              # will run only when on pull requests with source branch names starting with the 'issues' string, or elease branches
            branches:
              only:
                - 1.20.x
                - 1.25.x
                - 1.30.x
                - 3.0.x
                - 3.1.x
                - /^*.x/
                - /^issues*/
              # will not run on pull requests from
              #
              # ignore:
                # - /^fix*/
                # - /^*support/
                # - /^*snyk*/
                # - /^*dependabot*/
  a_first_workflow:
    jobs:
      - yet_another_test_job:
          context: gravitee-lab
      - a_first_test_job:
          context: gravitee-lab
          requires:
            branches:
              # will not run on pull requests from
              #
              ignore:
                - /^fix*/
                - /^*support/
                - /^*snyk*/
                - /^*dependabot*/
                - 1.20.x
                - 1.25.x
                - 1.30.x
                - 3.0.x
                - 3.1.x
                - /^*.x/
                - /^issues*/
